[workspace.scripts]
game = "src/main.luau"

[runtime.debug]
detailed_error = true

[runtime.luau.options]
debug_level = 2
optimization_level = 1
native_code_gen = true

[resolvers.formatter]
max_depth = 4
use_color = true
table_address = true
recursive_Table = false
buffer_max_display = 48
